### PR TITLE
add 3d poi visualization layer for MeshGenerationPois demo

### PR DESCRIPTION
**Pull request by brnkhy**

### CODE REVIEW

**Comment by david-rhodes** [comment]
@brnkhy Did you want to rename `ILabelVisualizationHelper` first, and maybe remove the need for `FeatureBehaviour`? It feels coupled, right now.

**Comment by brnkhy** [comment]
@david-rhodes `feature behaviour` is different, I add that to everything and it just contains the raaw data for easier debugging. So it's not a poi thing.
`ILabelVisualizationHelper` is used to pass feature data to prefabs, that's all. And yes we should rename that, you like `IPoiPrefabHelper` ?

**Comment by david-rhodes** [comment]
@brnkhy I just checked this and 3D poi is not default in the visualizer. Was it intended to be?

**Comment by brnkhy** [comment]
@david-rhodes sorry I just realized I didn't include asset files in that commit, pushed them as well, it should be there now.

**Pull request merged**
