### PR TITLE
Change TileProviders to update only when Map changes.

### PR DESCRIPTION
**Pull request by atripathi-mb**
**Description of changes**

TileProviders calculate extent on every Update loop. This is wasteful, especially for static maps. 
This PR changes the extent calculation to occur only when the map have changed. 

**QA checklists**

- [x] Add relevant code comments. Every API class and method should have `<summary>` description as well as description of parameters.
- [ ] **Add tests for new/changed/updated classes and methods!!!**
- [x] Check out conventions in [CONTRIBUTING.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CONTRIBUTING.md).
- [x] Check out conventions in [CODING-STYLE.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CODING-STYLE.md)
- [ ] Update the [changelog](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/05-changelog.md)
- [ ] Update documentation.

**Reviewers**
@brnkhy @greglemonmapbox

### CODE REVIEW

**Comment by greglemonmapbox** [comment]
Additional RangeAroundTransform bug details. If I attempt to use RangeAroundTransform as an initial map option, it does not work correctly. If I then use camera bounds and attach camera movement script to cam, that works correctly. If I then use RangeAroundTransform option again, it does work correctly.

**Comment by brnkhy** [comment]
@atripathi-mb testing this out. Camera Bounds tile provider doesn't seem to remove tiles out of FOV, this isn't intentional right? TileProvider returns all tiles in the "active tiles" list, not sure why so far though.

**Comment by brnkhy** [comment]
@atripathi-mb have you merged other stuff into this branch as well? I see CitySimulator scene settings changed and there seems to be an issue with memory.

looks like a leak but it doesn't show any gc allocation in any functions either so I'm confused.

**Comment by brnkhy** [comment]
@atripathi-mb I'm afraid I have no idea but I'll check sometime. I'm not even sure if it's tile provider directly but probably something related. profiler really isn't helping. I gotta find a way to fix/hack that somehow.

**Pull request merged**
