### PR TITLE
Allow MonoBehaviour message inheritance

### LINKED ISSUE #647: Abstract classes that implement Monobehaviour routines should allow for inheritance via protected virtual access modifiers.
I've made this point before in other issues I've submitted and I just updated to 1.4.0 where the issue persists.

If AbstractMap.cs is intended to be abstract and built upon further to create specialized maps, the use of Awake, Start, and other MonoBehaviour methods may need to be modified.

In my specific case, I would like to use Awake() and Start() in my inherited class, but am blocked from doing so by the inexplicit private modifiers on those methods.

```
void Awake()...
void Start()...
```

should be replaced with

```
protected virtual void Awake()...
protected virtual void Start()...
```

Because both of these are blocked, I am unable to run a related method without modifying the Mapbox source.

e.g.
```
protected override void Start()
{            
    base.Start();
    Root.parent.GetComponentsInChildren<SphereCapper>().ToList().ForEach(sc => sc.GenerateCapMesh());
}
```

I am willing to do a pull request for this change, but I understand that access modifiers should be left to Mapbox's discretion.

### PR DESCRIPTION
**Pull request by ahokinson**
Removes private modifier restrictions from Mapbox Unity classes that inherit from MonoBehaviour. Applies protected virtual modifier to any use of MonoBehaviour Messages detailed here: https://docs.unity3d.com/ScriptReference/MonoBehaviour.html

**Related issue**

Relates to #647.
Closes #647.

**Description of changes**

Used `grep` to find all instances of `MonoBehaviour` messages in `sdkproject/Assets/Mapbox/Unity`.

```
grep -r 'Awake()\|FixedUpdate()\|LateUpdate()\|OnAnimatorIK()\|OnAnimatorMove()\|OnApplicationFocus()\|OnApplicationPause()\|OnApplicationQuit()\|OnAudioFilterRead()\|OnBecameInvisible()\|OnBecameVisible()\|OnCollisionEnter()\|OnCollisionEnter2D()\|OnCollisionExit()\|OnCollisionStay()\|OnCollisionStay2D()\|OnConnectedToServer()\|OnControllerColliderHit()\|OnDestroy()\|OnDisable()\|OnDisconnectedFromServer()\|OnDrawGizmos()\|OnDrawGizmosSelected()\|OnEnable()\|OnFailedToConnect()\|OnFailedToConnectToMasterServer()\|OnGUI()\|OnJointBreak()\|OnJointBreak2D()\|OnMasterServerEvent()\|OnMouseDown()\|OnMouseDrag()\|OnMouseEnter()\|OnMouseExit()\|OnMouseOver()\|OnMouseUp()\|OnMouseUpAsButton()\|OnNetworkInstantiate()\|OnParticleCollision()\|OnParticleTrigger()\|OnPlayerConnected()\|OnPlayerDisconnected()\|OnPostRender()\|OnPreCull()\|OnPreRender()\|OnRenderImage()\|OnRenderObject()\|OnSerializeNetworkView()\|OnServerInitialized()\|OnTransformChildrenChanged()\|OnTransformParentChanged()\|OnTriggerEnter()\|OnTriggerEnter2D()\|OnTriggerExit()\|OnTriggerExit2D()\|OnTriggerStay()\|OnTriggerStay2D()\|OnValidate()\|OnWillRenderObject()\|Reset()\|Start()\|Update()' --exclude-dir=sdkproject/Assets/Mapbox/Unity/Editor sdkproject/Assets/Mapbox/Unity
```

Ignored `Editor` subfolder because custom editors for inherited classes can still draw the inherited inspector.

**QA checklists**

- [ ] Verify previous access to methods via inheritance is unaffected.

**Reviewers**

@atripathi-mb

### CODE REVIEW

**Comment by atripathi-mb** [comment]
@ahokinson Thanks for the PR, this will be great improvement to our API's. Going forward we will add this to our coding practice. 

We are preparing for a minor release tentatively next week. We are currently under code freeze. Will include this PR in the next release.

**Comment by ahokinson** [comment]
Made a small bug fix to `GlobeTileProvider.cs` where TileCover was attempted every frame.

This might have gone unnoticed because the TileProvider would prevent adding duplicate tiles.

```
protected virtual void AddTile(UnwrappedTileId tile)
{
	if (_activeTiles.ContainsKey(tile))
	{
		return;
	}
...
```

The initial change was made in https://github.com/mapbox/mapbox-unity-sdk/commit/c14dca22c344101182d4cd8d926f8d06ceb1befb. If it was addressing the status event issue, I don't believe needlessly running in `Update()` is the right solution.

**Comment by brnkhy** [comment]
I eye-checked the files and run some demo scenes, all looks fine to me. good fix/improvement 👍

**Comment by ahokinson** [comment]
Is there a reason why this hasn't been merged?

**Comment by atripathi-mb** [comment]
@ahokinson We are working on a next release, will be merged after some other feature PR's are merged. This PR is slated to be on the next release. Thanks for your patience.

**Pull request merged**
