### PR TITLE
Adding using for Mathd and Vector2d

### PR DESCRIPTION
**Pull request by bourgeoismaxime**
Suggestion #631
Adding using for Mathd and Vector2d to prevent potential errors for "ambigious call between UnityEngine and Mapbox.Utils".

### CODE REVIEW

**Comment by bourgeoismaxime** [comment]
There are still some using missing. Going to fix that.

**Comment by atripathi-mb** [comment]
@brnkhy @BergWerkGIS Can you take a look at this PR please?

**Comment by BergWerkGIS** [comment]
@bourgeoismaxime 
I'm not sure I follow why this change is needed. 
Could you elaborate?

It's adding
```c#
using Vector2d = Mapbox.Utils.Vector2d;
```

but as we already have

```c#
using Mapbox.Utils;
```
`Vector2d` will automatically evaluate to `Mapbox.Utils.Vector2d`.

Furthermore I'm not aware of a `Vector2d` class in `UnityEngine`.
Maybe you mixed that up with [`Vector2`](https://docs.unity3d.com/ScriptReference/Vector2.html) (no `d`)?
image

**Comment by atripathi-mb** [comment]
Closing pull request since adding appropriate namespaces can avoid ambiguous class names.

**Pull request closed without merging**
