### PR TITLE
[WIP] SDK Plug and Play -  Don't Merge yet

### PR DESCRIPTION
**Pull request by atripathi-mb**
**Related issue**

Addresses SDK Plug & Play. 

**Description of changes**

Major refactor related to SDK Plug & Play epic. These changes create a simplified UI & API for Maps. These changes are aimed at enabling users to create a map in the scene with minimum time and effort. This work will provide users with prefabs for common use cases and startup times of under a minute. 

** NOT READY FOR MERGE YET **

** IMPORTANT NOTES ** 
- [ ] Examples scenes are broken, will need to fix them. 
- [ ] To test , use the PoGoPlug&Play scene under 8_PoGOPlug&Play folder. 
- [ ] Report any missing functionality or API calls. 

**QA checklists**

- [ ] Add relevant code comments. Every API class and method should have `<summary>` description as well as description of parameters.
- [ ] **Add tests for new/changed/updated classes and methods!!!**
- [ ] Check out conventions in [CONTRIBUTING.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CONTRIBUTING.md).
- [ ] Check out conventions in [CODING-STYLE.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CODING-STYLE.md)
- [ ] Update the [changelog](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/05-changelog.md)
- [ ] Update documentation.

**Reviewers**

cc @brnkhy @BergWerkGIS @isiyu @morgane

### CODE REVIEW

**Comment by BergWerkGIS** [comment]
@atripathi-mb forgot to check in changes to `VectorTile.cs`?
image

May I suggest merging `develop` to see if there are any conflicts?
You can do that (having your branch checked out) with
```
git pull origin develop
```

**Comment by atripathi-mb** [comment]
@BergWerkGIS 
> May I suggest merging develop to see if there are any conflicts?

Already done, please let me know if you see any conflicts or missing files please.

**Comment by BergWerkGIS** [comment]
Checked some scenes, all are missing the script on `Map`:
image

**Comment by atripathi-mb** [comment]
@BergWerkGIS  
> Checked some scenes, all are missing the script on Map: 

Yes, haven't got a chance to go through the example scenes yet. Added notes to the PR about this. Use PoGOPlug&Play scene for testing or create a new scene. 

This PR is still a WIP.

**Pull request closed without merging**
