### PR TITLE
 Fix for issue #264

### PR DESCRIPTION
**Pull request by atripathi-mb**
Pan on mouse drag instead of mouse up.

### CODE REVIEW

**Comment by david-rhodes** [comment]
@atripathi-mb was the intention for scrolling to continue if just holding mouse button down (and not moving the pointer)? Because right now it appears that there is a constant pan, even when my mouse is stationary (and it seems to be accelerating?).

**Comment by atripathi-mb** [comment]
@david-rhodes Good catch, wasn't intentional but I kind of like it ;) Pushed a fix for it though.

**Comment by david-rhodes** [comment]
For clarity, is this fix included in: https://github.com/mapbox/mapbox-unity-sdk/pull/321? If so, do we need this PR?

**Comment by atripathi-mb** [comment]
I can roll this into #321 . Have to port it to QuadTreeCamera anyway. Feel free to discard

**Comment by david-rhodes** [comment]
Done in #321

**Pull request closed without merging**
