### PR TITLE
MapboxAR UX Commit

### PR DESCRIPTION
**Pull request by ufktvfk**
Added a UX/UI to world calibration. Using the fiisrt compass value when the app starts and walking along a straight line greatly increases the accuraracy of World Calibration.  WorldScaleAR scene now has a more user friendly world calibration.

**QA checklists**

- [ ] Add relevant code comments. Every API class and method should have `<summary>` description as well as description of parameters.
- [ ] **Add tests for new/changed/updated classes and methods!!!**
- [ ] Check out conventions in [CONTRIBUTING.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CONTRIBUTING.md).
- [ ] Check out conventions in [CODING-STYLE.md](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/CODING-STYLE.md)
- [ ] Update the [changelog](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/05-changelog.md)
- [ ] Update documentation.

**Reviewers**

Tag your reviewer(s). Choose wisely.

### CODE REVIEW

**Comment by BergWerkGIS** [comment]
Sounds great, going to try it later today.

> Using the fiisrt compass value when the app starts 

The next iteration of the `DeviceLocationProvider` will have something similar per default:
https://github.com/mapbox/mapbox-unity-sdk/blob/ad9e67211ef90c071e67b8e6ecac2e388d3cb19d/sdkproject/Assets/Mapbox/Unity/Location/DeviceLocationProvider.cs#L279-L289

**Comment by ufktvfk** [comment]
Yes, we take initial userHeading and walk along a very straight line to align with this initialHeading. Then, we calculate GPS offsets between GPS update points(red, moving arrows).  If gps updates's accuracy is high like less than 10 meters, we get very good aligment. If we are not okay with aligment, we can manually calibrate by moving ARRoot which is actually First Person Camera. So instead of moving Map gameobject, we actually move ourselves and look at the map a different pose.

**Comment by BergWerkGIS** [comment]
@ufktvfk could you please elaborate what's going on here and why there are so many changed files:

image

eg why delete the root `.gitignore`?

I'm not able to skim through the changes as my whole system almost grinds to a stop trying to look at the `Files changed` tab.

I cloned directly from your repo:
* Opening `develop` crashes `Unity@2017.4.2f2`.
* Opening with `Unity@2018.2.0b4` works but I get three errors associated with `GoogleARCore`:
image

**Comment by BergWerkGIS** [comment]
After deleting
```
GoogleARCore/Examples/CloudAnchor/
```
errors disappeared but I got this:

image

Nevertheless I was able to build to an Android device (running Android 8.0.0) but unfortunately I get an error that my device is not compatible with latest ARCore version.

**Comment by BergWerkGIS** [comment]
Sideloaded `ARCore_1_2.apk` from https://github.com/google-ar/arcore-android-sdk/releases but app keeps crashing.

**Comment by ufktvfk** [comment]
What is your phone model?

**Comment by ufktvfk** [comment]
Can you get an apk from this project: 
https://www.dropbox.com/s/ahgte3c1gg7196y/WorldScaleARUX.rar?dl=0

Sorry about issues you get. I must have done something wrong in committing.

**Comment by BergWerkGIS** [comment]
> What is your phone model?

Yeah, that's probably the issue: OnePlus 3.
Don't have my other devices at hand right now (will try again next week).

> Sorry about issues you get. I must have done something wrong in committing.

To get this PR merged please clean it up and try to bring down the number of changed files as much as possible.
We can't evaluate if we can't pinpoint what has actually changed.

If you outline the steps you took and what the requirements are to run it we might be able to help. 
eg.:
* did you upgrade `UnityARInterface`? to which commit?
* is `Unity@2018` a requirement? doesn't seem to work with 2017 - at least for me
* ...

**Pull request closed without merging**
