### PR TITLE
Upgrade telem libraries

### PR DESCRIPTION
**Pull request by david-rhodes**
Fixes iOS-related issues in: https://github.com/mapbox/mapbox-unity-sdk/issues/101

Also adds method to enable/disable location collection, and hooked up to attribution buttons.

### CODE REVIEW

**Comment by isiyu** [comment]
@david-rhodes  Seeing this on Android builds, loaded okay initially; but closed the app and  crashed on relaunch. 
hardware is LG G3; Android 5.0.1

screen shot 2017-07-25 at 4 17 37 pm

**Comment by david-rhodes** [comment]
@isiyu before you get this exception, do you get any logs from Unity that look something like those that come from this method: https://github.com/mapbox/mapbox-unity-sdk/blob/f6aaef41844885b39bdafc13a28e05848f630731/sdkproject/Assets/Mapbox/Unity/Telemetry/TelemtryAndroid.cs#L20?

The error seems to suggest that `telemInstance` is null, so I would expect previous errors.

FWIW, I cannot reproduce on my Pixel.

/cc @zugaldia

**Comment by BergWerkGIS** [comment]
Not able to repdocue on either of my devices: Android 7.0 and 7.1.1.

**Comment by zugaldia** [comment]
The error seems to come from [this line](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java#L601) when the `locationEngine` is `null`, which should never be the case as long as the module has been initialized with `initialize`. This could indicate an issue with the current set up in Unity, meanwhile I've ticketed https://github.com/mapbox/mapbox-java/issues/523 to avoid the exception and log an error message that could help us troubleshoot the problem.

**Comment by isiyu** [comment]
@david-rhodes Looks like this may have been a bad build on my device. I deleted the app on the phone and did a fresh build and that seemed to have resolved it. (Built over the app with a few other demos using the same Package Name and all worked consistently.

**Pull request merged**
