### PR TITLE
Coding style

### PR DESCRIPTION
**Pull request by david-rhodes**
First pass coding style. Link is set to develop for when this is merged.

Can we all agree on these? Should we make a note about fixing any existing code that does not already follow these standards?

### CODE REVIEW

**Comment by Spaxe** [comment]
As long as there are no mixed tabs with spaces in the same file, it should be OK?

**Comment by BergWerkGIS** [comment]
> First pass coding style. Link is set to develop for when this is merged.

@david-rhodes I changed that to be relative and stay in the same branch.
I think it doesn't make sense to pin to `develop`.

> As long as there are no mixed tabs with spaces in the same file, it should be OK?

@Spaxe we'd like to have tabs in all code files.

**Comment by david-rhodes** [comment]
@Spaxe the problem is that many of us use "auto-format" in our IDE. If we eventually modify a file that had pure spaces, the diff will show every line as being different. Makes changes hard to track.

**Comment by binakot** [comment]
I hope this link helps for the issue http://www.dofactory.com/reference/csharp-coding-standards

**Pull request merged**
