### PR TITLE
Enable scene changes without throwing NREs

### PR DESCRIPTION
**Pull request by david-rhodes**
To test: add several scenes to build settings. Add an scene change script like the one below to the first scene in the list. Quickly change between test scenes by clicking the left mouse button at runtime. Ensure no missing references exist and that maps load again upon reloading their scenes.

```cs
using System;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Mapbox
{
	public class SceneLoader : MonoBehaviour
	{
		int _currentSceneIndex = 1;

		void Awake()
		{
			DontDestroyOnLoad(gameObject);
		}

		void Update()
		{
			if (Input.GetMouseButtonUp(0))
			{
				SceneManager.LoadScene(_currentSceneIndex);
				_currentSceneIndex++;

                                // Your scene count here.
				if (_currentSceneIndex > 2)
				{
					_currentSceneIndex = 1;
				}
			}
		}
	}
}
```

### CODE REVIEW

**Comment by david-rhodes** [comment]
Reference: https://github.com/mapbox/mapbox-unity-sdk/issues/374

**Comment by david-rhodes** [comment]
@brnkhy Still getting some exceptions for certain scenes. Would be nice to get your eyes on this. I feel like so many null reference checks mean we did something wrong with regards to temporal coupling. 😢

**Comment by mecadiego113** [comment]
It won't work with `MergedModifierStack` right?

**Comment by brnkhy** [comment]
@david-rhodes I'm using that script but couldn't get any NRE (using three mesh generation demo scenes). I guess I'm doing something wrong? any ideas?

**Comment by david-rhodes** [comment]
Check scenes with merged modifier stacks? Clear you disk cache? Change scenes quickly during build process? Make sure coroutines are being used for visualizers?

**Comment by mecadiego113** [comment]
@brnkhy Try to perform a scene switch while map is initializing/loading and use `MergedModifierStack` for buildings layer

**Comment by brnkhy** [comment]
@david-rhodes @mecadiego113 managed to recreate it with merged mesh modifier as you suggested. 
cleared pool on initialize (map reset) and null check a tile object in layer visualizer. still testing it but I guess that did the trick, couldn't recreate so far.

**Comment by atripathi-mb** [comment]
@brnkhy Consistently able to reproduce the NRE with these steps:

**Enable coroutines for visualizers.** 

1. Add `MeshGeneration` scene as your first scene.
2. Add Drive example as your second scene
3. Press play
4. Switch to drive and again to MeshGeneration scene, and while the building are loading click to load Drive scene again. 

**Call Stack**
MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Mapbox.Examples.LoadingPanelController.<Awake>m__0 (ModuleState s) (at Assets/Mapbox/Examples/Scripts/LoadingPanelController.cs:21)
Mapbox.Unity.Map.AbstractMapVisualizer.set_State (ModuleState value) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:40)
Mapbox.Unity.Map.AbstractMapVisualizer.UpdateState (Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory factory) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:127)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.set_Progress (Int32 value) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:28)
Mapbox.Unity.MeshGeneration.Factories.FlatTerrainFactory.OnRegistered (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/FlatTerrainFactory.cs:68)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory.Register (Mapbox.Unity.MeshGeneration.Data.UnityTile tile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:64)
Mapbox.Unity.Map.AbstractMapVisualizer.LoadTile (UnwrappedTileId tileId) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:176)
Mapbox.Unity.Map.AbstractMap.TileProvider_OnTileAdded (UnwrappedTileId tileId) (at Assets/Mapbox/Unity/Map/AbstractMap.cs:175)
Mapbox.Unity.Map.AbstractTileProvider.AddTile (UnwrappedTileId tile) (at Assets/Mapbox/Unity/Map/AbstractTileProvider.cs:34)
Mapbox.Unity.Map.RangeTileProvider.OnInitialized () (at Assets/Mapbox/Unity/Map/RangeTileProvider.cs:20)
Mapbox.Unity.Map.AbstractTileProvider.Initialize (IMap map) (at Assets/Mapbox/Unity/Map/AbstractTileProvider.cs:23)
Mapbox.Unity.Map.BasicMap.Initialize (Vector2d latLon, Int32 zoom) (at Assets/Mapbox/Unity/Map/BasicMap.cs:21)
Mapbox.Unity.Map.AbstractMap.Start () (at Assets/Mapbox/Unity/Map/AbstractMap.cs:152)

**Comment by brnkhy** [comment]
@atripathi-mb I added a check for that loading panel as well. that was supposed to be a simple script but using lambda functions and that function runs after the game object is destroyed etc.

**Pull request merged**
