### PR TITLE
"Mapbox.IO.Compression-unity" binaries

### LINKED ISSUE #284: Provide DLLs for Mapbox.IO.Compression-unity
Dependency [`Mapbox.IO.Compression-unity`](https://github.com/mapbox/Mapbox.IO.Compression-unity) does not change often.
Provide binaries to be included with the SDK to reduce number of included source files and Unity compilation times.

### PR DESCRIPTION
**Pull request by BergWerkGIS**
* closes #284 
* removes submodule `dependencies/Mapbox.IO.Compression-unity`
* adds assemblies (DLLs) for Net3.5 and UWP
* tested on
  * ✅  Windows native x64
  * ✅  Android
  * UWP: problems see below
------

When testing this branch make sure to run
* Windows: `update-mapbox-unity-sdk-core.bat`
* Linux/OSX: `./update-mapbox-unity-sdk-core.sh`

after checkout to get rid of the submodule and get the new DLLs.

**And also when checking out another branch afterwards!**

------

### Having troubles with the `meta` files and UWP builds.

Using these settings :
* Net35 DLL (`Any Platform` / `Exclude Platforms`):
  image
* UWP DLL (`Include Platforms`):
  image

and exporting to `Windows Universal Platform` I get error `'dll' is used from several locations`:

image

**Why?**

-------

When explicitly stating `Include Platforms` for both DLLs

image image

export works expected.

But that's not what I want as being on Windows I cannot set properties eg for `iOS` platform.

### CODE REVIEW

**Comment by david-rhodes** [comment]
@BergWerkGIS For some reason, Unity only exposes the platforms that you currently have modules installed for. The best approach is likely to copy properties directly from the JSON plugin meta files, as those have already been sorted (manually).

**Comment by BergWerkGIS** [comment]
@david-rhodes 

> For some reason, Unity only exposes the platforms that you currently have modules installed for.

Yes, but isn't that a bug in Unity?

Why does the **`Net35`** assembly get included (`'dll' is used from several locations`) when exporting to **`UWP`** using these settings on it:
*  `Any Platform` / `Exclude Platforms`
  image

As I understand it, it should be used for **all** platforms _**except**_ `UWP`, no?

**Comment by BergWerkGIS** [comment]
Yes, indeed a Unity bug, which should be solved with `2017.3.0a7`:
https://issuetracker.unity3d.com/issues/dll-files-are-not-excluded-during-building-for-standalone-platform-even-though-they-are-selected-to-be-excluded

I was able to reproduce that issue being solved with `2017.3.0.b5`.

I suppose for the time being we have to stick with explicit `include` settings.
Will update using `meta`s from `Mapbox.Json` soon.

**Comment by BergWerkGIS** [comment]
Ready for review.

Please test on as many platforms as possible: OSX, Windows, iOS, Andoird.

**Comment by david-rhodes** [comment]
- [ ] iOS (6s+, iOS 11)
- [ ] Android (Pixel)
- [ ] WebGL 
- [ ] OSX standalone

**Comment by david-rhodes** [comment]
@BergWerkGIS You tested UWP and all is good?

**Comment by BergWerkGIS** [comment]
Exporting UWP project and building that works.
Deploying the built UWP app to the HoloLens Emulator still crashes on my machine, see #239

**Pull request merged**
