### PR TITLE
Fix C# warnings (thrown in Unity editor)

### PR DESCRIPTION
**Pull request by david-rhodes**
Note that this does not include additional warnings thrown in your IDE (Unity filters many of these--`[SerializeField]`, for example).

There's also some obsolete file and namespace cleanup.

Edit: note that this **does not** include warnings in dependencies: https://github.com/mapbox/vector-tile-cs/pull/33 and https://github.com/mapbox/Mapbox.IO.Compression-unity/pull/1

### CODE REVIEW

**Comment by david-rhodes** [comment]
Fixes: https://github.com/mapbox/mapbox-unity-sdk/issues/178

**Comment by brnkhy** [comment]
ran few demos, couldn't see any warning at all (is that normal? I mean zero warnings). looks good to me

**Comment by david-rhodes** [comment]
@BergWerkGIS Just waiting on mapbox/Mapbox.IO.Compression-unity#1 to be approved and submodule bumped.

**Comment by BergWerkGIS** [comment]
✅ bump `Mapbox.IO.Compression-unity`
✅ fix some more warnings in UnitTests

lgtm to merge.

**Pull request merged**
